require('dotenv').config();
const express=require('express'),cors=require('cors'),helmet=require('helmet'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),{Pool}=require('pg'),path=require('path');
const app=express(),PORT=process.env.PORT||10000,SECRET=process.env.JWT_SECRET||'dev-secret-change-me';
if(!process.env.DATABASE_URL) console.warn('DATABASE_URL missing');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL&&!process.env.DATABASE_URL.includes('localhost')?{rejectUnauthorized:false}:false});
app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const data=[
['iSAN Computers Education','2-161/1, 2nd Floor, Thadala Complex, Bhanugudi Junction, Kakinada, Andhra Pradesh 533003','Bhanugudi Junction','8978989444','http://www.isan.oc.in/',['C / C++','Java','Python','Web Designing','.NET','Tally','AutoCAD','MS Office','CCNA','Node.js','Hardware & Networking']],
['Learntact Learning Center','1st Floor, Subhamasthu Showroom, D.No. 20-11-40, Majestic Street, Suryanarayana Puram, Kakinada, Andhra Pradesh 533001','Suryanarayana Puram','6303114238','https://www.learntact.com/',['Python','Java','C','C++','MS Office','AutoCAD','Pro-E','CATIA','Vedic Maths','Chess']],
['Data Lineage','1st floor, above Shanvi Diagnostic Centre, beside Bhanu Multi Speciality Hospital, G.O. Colony, Kakinada, Andhra Pradesh 533003','G.O. Colony','7989940140','https://www.datalineage.in/',['AWS Cloud','Python','MySQL','PySpark','Data Engineering']],
['5XFUTURE Software Training Institute','68-10-35, Vidhyuth Nagar, SBI Officers Colony, Ramanayyapeta, Kakinada, Andhra Pradesh 533003','Ramanayyapeta','9640313555','https://5xfuture.in/',['Python','Java Full Stack','Full Stack Development','AI & ML','Data Science','Cybersecurity','C / C++','Digital Marketing','Soft Skills / Corporate Communication']],
['Agasthya Solutions','Ground Floor, Sri Naga Vigneshwara Nilayam, 2-34-14, Chinta Vari Street, opposite Mamatha Diagnostic Centre, Perrajupeta, Kakinada, Andhra Pradesh 533003','Perrajupeta','8019465669','http://www.agasthyasolutions.com/',['AWS / Cloud','DevOps','Python','Digital Marketing','Tally','Photoshop','Internships / Industrial Training','Soft Skills & Communication','Mock Interviews','Resume / LinkedIn Support']],
['CAD DESK Kakinada','D.No. 2-43-3, 3rd Floor, 50 Buildings Center, Bhaskar Nagar, Ramanayyapeta, Kakinada, Andhra Pradesh 533003','Bhaskar Nagar / Ramanayyapeta','9032444388','https://caddeskindia.com/center/best-autocad-training-institute-kakinada/',['AutoCAD','STAAD Pro','Revit Architecture','Revit Structure','3DS Max','V-Ray','Google SketchUp','BIM Modelling','SolidWorks','CATIA','Fusion 360','ANSYS','NX CAM','CNC','AutoCAD Electrical','MATLAB','PLC','SCADA']],
['KTS – Software Training Institute','RTC Complex Road, Bhanugudi Junction, Perrajupeta, Kakinada, Andhra Pradesh 533003','Bhanugudi Junction','9553084240','',[]],
['SICE Computer Education','214, National Highway, G.O. Colony, Kakinada, Andhra Pradesh 533003','G.O. Colony','9912300248','',['Computer Education / Skill Training']],
['Suryalakshmi Inspection & Technical Services (SITSNDT)','16-33-67/3, First Street, Sambamurthy Nagar, Kakinada, Andhra Pradesh 533003','Sambamurthy Nagar','9193917777','http://www.sitsndt.com/',['NDT / Inspection & Technical Skills']],
['Enlighten Institute of Trainings','6-187, Ramareddy Nagar, Kakinada, Andhra Pradesh 533006','Ramareddy Nagar','9391236898','https://www.enlightentrainings.com/',['Training Programmes']],
['SkillPundit Career','Paradise Central, D.No. 39-2-11, Gandhi Chowk, Suryanarayana Puram, Kakinada, Andhra Pradesh 533001','Gandhi Chowk','','http://www.skillpundit.com/',['Career-oriented Training & Skill Development']],
['Skill Shine','Prakasam St, opposite Med Quest, Rama Rao Peta, Kakinada, Andhra Pradesh 533004','Rama Rao Peta','9849692827','https://skillshineoverseas.netlify.app/',['IELTS','PTE','SAT','Interview Skills','Spoken English','NEET Biology','Study Abroad Preparation']],
['Government ITI, Kakinada','Ramanayyapeta, Kakinada, Andhra Pradesh 533003','Ramanayyapeta','8842348182','https://govtitikakinada.org/',['ITI Trade-based Technical Training']],
['KGR Vocational Junior College','Vivek Street, Sri Vidya Colony, Jayendra Nagar, Siddartha Nagar, Kakinada, Andhra Pradesh 533003','Siddartha Nagar','8500297129','',['Vocational Education / Training']],
['MK Technologies','Near Musallamma Gudi Center, Samarlakota Road, opposite Sri Pavan Medicals, Madhavapatnam, Kakinada','Madhavapatnam','','',['Web Designing','DBMS','Software Testing','Python','Photoshop','Computer Applications','Tally','C / C++','Visual Basic','Multimedia']],
['Skillinduce Private Limited','II Floor, Srishti Building, 64-4-11/7, Pratap Nagar, Kakinada, Andhra Pradesh 533004','Pratap Nagar','8971717105','https://www.skillinduce.co.in/',['Software / IT Skills Training']],
['Odigos Software Training Institute','D.No. 10-407/A, Eswar Nagar, 3 APSP Camp, Ramanayyapeta, Kakinada, Andhra Pradesh 533005','Ramanayyapeta','','',['Software Training']],
['Kakinada Institute of Software & Hardware','1-13-6, Bhanugudi Junction, opposite Prasanti Castle, Srinagar, Kakinada, Andhra Pradesh 533001','Bhanugudi Junction','9948552767','',['Software & Hardware Training']],
['BDPS Computer Education','Sai Prameela Apartments, Nagamallithota Junction, opposite Alluri Sitarama Raju Statue, Ramanayyapeta, Kakinada, Andhra Pradesh 533003','Nagamallithota','8142668889','http://www.bdpsit.com/',['Computer / Coding Training']],
['SRI BABU COMPUTER TRAINING INSTITUTE, SAP FICO','Indrapalem Bridge, beside Friends Net & Net Centre, Indrapalem, Kakinada, Andhra Pradesh 533006','Indrapalem','6303454062','',['SAP FICO','Computer Training']],
['Janahita Training and Placements','Building Centre, D.No. 2-43, Bhaskar Nagar, Dwaraka Nagar, Ramanayyapeta, Kakinada, Andhra Pradesh 533003','Bhaskar Nagar / Ramanayyapeta','9348223345','http://janahitaplacements.com/',['Training & Placement Programs']],
['Ardha Technologies','Upstairs, Bakers Inn Complex, 2-1-67, Bhanugudi Junction, beside Anand Theatre, G.O. Colony, Kakinada, Andhra Pradesh 533003','Bhanugudi Junction','9246678976','http://www.tallyservices.co/',['Tally','Tally Support / Services']],
['SAP Training – Thanishaka Technologies','Kotta Kakinada Road, backside of RTC Complex, Shanthi Nagar, Kakinada, Andhra Pradesh 533003','Shanthi Nagar','9010576607','http://thanishkatech.blogspot.in/',['SAP Training','SAP-related Software Training']],
['NIT Kakinada','10-9-49, Nageswara Rao Street, Bhanugudi Junction, Rama Rao Peta, Kakinada, Andhra Pradesh 533003','Bhanugudi Junction','9000136669','',['Technical / Vocational Training']]
];
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS centers(id SERIAL PRIMARY KEY,name VARCHAR(180) UNIQUE NOT NULL,address TEXT NOT NULL,area VARCHAR(120),phone VARCHAR(40),website TEXT,latitude DOUBLE PRECISION,longitude DOUBLE PRECISION);CREATE TABLE IF NOT EXISTS courses(id SERIAL PRIMARY KEY,center_id INT REFERENCES centers(id) ON DELETE CASCADE,course_name VARCHAR(180) NOT NULL,UNIQUE(center_id,course_name));`);for(const c of data){let r=await pool.query(`INSERT INTO centers(name,address,area,phone,website) VALUES($1,$2,$3,$4,$5) ON CONFLICT(name) DO UPDATE SET address=EXCLUDED.address,area=EXCLUDED.area,phone=EXCLUDED.phone,website=EXCLUDED.website RETURNING id`,c.slice(0,5));for(const course of c[5])await pool.query(`INSERT INTO courses(center_id,course_name) VALUES($1,$2) ON CONFLICT(center_id,course_name) DO NOTHING`,[r.rows[0].id,course]);}}
function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({error:'Login required'})}}
app.get('/api/health',async(_,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(500).json({ok:false})}});
app.post('/api/register',async(req,res)=>{const{name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Name, email and password (6+ characters) are required'});try{const h=await bcrypt.hash(password,12),r=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email',[name.trim(),email.trim().toLowerCase(),h]);const u=r.rows[0],token=jwt.sign(u,SECRET,{expiresIn:'7d'});res.status(201).json({token,user:u})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Email already registered':'Registration failed'})}});
app.post('/api/login',async(req,res)=>{try{const r=await pool.query('SELECT * FROM users WHERE email=$1',[String(req.body.email||'').trim().toLowerCase()]),u=r.rows[0];if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Invalid email or password'});const user={id:u.id,name:u.name,email:u.email},token=jwt.sign(user,SECRET,{expiresIn:'7d'});res.json({token,user})}catch{res.status(500).json({error:'Login failed'})}});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));
app.get('/api/centers',async(req,res)=>{try{const q=String(req.query.q||'').trim(),course=String(req.query.course||'').trim();let p=[],w=[];if(q){p.push('%'+q+'%');w.push(`(c.name ILIKE $${p.length} OR c.address ILIKE $${p.length} OR c.area ILIKE $${p.length})`)}if(course){p.push('%'+course+'%');w.push(`EXISTS(SELECT 1 FROM courses x WHERE x.center_id=c.id AND x.course_name ILIKE $${p.length})`)}const r=await pool.query(`SELECT c.*,COALESCE(json_agg(json_build_object('id',co.id,'name',co.course_name)) FILTER(WHERE co.id IS NOT NULL),'[]') courses FROM centers c LEFT JOIN courses co ON co.center_id=c.id ${w.length?'WHERE '+w.join(' AND '):''} GROUP BY c.id ORDER BY c.name`,p);res.json({centers:r.rows})}catch(e){console.error(e);res.status(500).json({error:'Could not load centres'})}});
app.get('/api/centers/:id',async(req,res)=>{const r=await pool.query(`SELECT c.*,COALESCE(json_agg(json_build_object('id',co.id,'name',co.course_name)) FILTER(WHERE co.id IS NOT NULL),'[]') courses FROM centers c LEFT JOIN courses co ON co.center_id=c.id WHERE c.id=$1 GROUP BY c.id`,[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Centre not found'});res.json({center:r.rows[0]})});
app.get('/api/nearest',async(req,res)=>{const lat=Number(req.query.lat),lng=Number(req.query.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'Valid location required'});const r=await pool.query(`SELECT c.*,COALESCE(json_agg(json_build_object('id',co.id,'name',co.course_name)) FILTER(WHERE co.id IS NOT NULL),'[]') courses FROM centers c LEFT JOIN courses co ON co.center_id=c.id WHERE c.latitude IS NOT NULL AND c.longitude IS NOT NULL GROUP BY c.id`);const h=(a,b,c,d)=>{const R=6371,dl=(c-a)*Math.PI/180,do_=(d-b)*Math.PI/180,x=Math.sin(dl/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(do_/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};res.json({centers:r.rows.map(x=>({...x,distanceKm:+h(lat,lng,+x.latitude,+x.longitude).toFixed(2)})).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,15),coordinatesAvailable:r.rows.length>0})});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public/index.html')));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
